using Rakt.EventsService.Application;
using Rakt.EventsService.Infrastructure;
using Rakt.EventsService.Presentation.Extensions;
var builder = WebApplication.CreateBuilder(args);
builder.AddStandardConfiguration();
builder.Services.AddEventsApplication();
builder.Services.AddEventsInfrastructure(builder.Configuration);
var app = builder.Build();
app.UseStandardConfiguration();
app.Run();
