using Rakt.BookingsService.Application;
using Rakt.BookingsService.Infrastructure;
using Rakt.BookingsService.Presentation.Extensions;
var builder = WebApplication.CreateBuilder(args);
builder.AddStandardConfiguration();
builder.Services.AddBookingsApplication();
builder.Services.AddBookingsInfrastructure(builder.Configuration);
var app = builder.Build();
app.UseStandardConfiguration();
app.Run();
