using Rakt.UsersService.Application;
using Rakt.UsersService.Infrastructure;
using Rakt.UsersService.Presentation.Extensions;
var builder = WebApplication.CreateBuilder(args);
builder.AddStandardConfiguration();
builder.Services.AddUsersApplication();
builder.Services.AddUsersInfrastructure(builder.Configuration);
var app = builder.Build();
app.UseStandardConfiguration();
app.Run();
