@host = http://localhost:5007
@id = 23bca9a2-156d-414c-8ee3-b11658e187bb

### Получить все события
GET {{host}}/events
Accept: application/json
###



### Получить событие по Id
GET {{host}}/events/{{id}}
Accept: application/json
###



### Создать событие
POST {{host}}/events
Content-Type: application/json

{
"title": "Встреча команды",
"description": "Обсуждение спринта",
"startAt": "2026-03-23T10:00:00",
"endAt": "2026-04-25T11:00:00"
}
###



### Обновить событие
PUT {{host}}/events/{{id}}
Content-Type: application/json
{
"title": "Обновленная встреча",
"description": "Изменили повестку",
"startAt": "2026-03-22T12:00:00",
"endAt": "2026-03-27T13:00:00"
}
###


### Удалить событие
DELETE {{host}}/events/{{id}}
###

### Должно быть 405
PATCH {{host}}/events/{{id}}
###

### Должно быть 404
GET {{host}}/event
###

